<?php

class dahdi_sangoma {
    private $data_store = array();
    private $sangoma_settings = array(
        "dahdimode" => "no",
        "t1mode" => "T1"
    );
    public function datastore() {
    }
    public function get_sangoma_settings() {
        $sql = "SELECT `settings` FROM dahdi_modules WHERE `module_name` = 'sangoma'";
        $o = sql($sql,'getOne');
        if($o) {
            return json_decode($o,TRUE);
        } else {
            return $this->sangoma_settings;
        }
    }
    public function settings() {
        $settings = $this->get_sangoma_settings();
        $output['title'] = 'Sangoma Settings';
        $output['reboot'] = true;
        $output['dialog']['height'] = 400;
        $output['dialog']['width'] = 500;
        $output['html'] = <<< EOF
            <h2>Sangoma Settings</h2>
            <h3>This edits all settings in /etc/wanpipe/global.conf</h3>
            <hr />
            <table width="100%" style="text-align:left;">
                <tr>
                    <td style="width:10px;">
                        <label for="sangoma_dahdimode">Run Wanpipe In DAHDI Mode:</label>
                    </td>
                    <td>
                        <select name="sangoma_dahdimode" id="sangoma_dahdimode">
EOF;
        $no = $settings['dahdimode'] == 'no' ? 'selected' : '';
        $yes = $settings['dahdimode'] == 'yes' ? 'selected' : '';
        $output['html'] .= '<option value="no" '.$no.'>No</option>';
        $output['html'] .= '<option value="yes" '.$yes.'>Yes</option>';
        $none = $settings['dahdimode'] == 'no' ? 'display:none;' : '';
        $output['html'] .= <<< EOF
                        </select>
                    </td>
                </tr>
                <tr id="sangoma_t1mode" style="$none">
                    <td style="width:10px;">
                        <label for="sangoma_t1mode">T1 Mode:</label>
                    </td>
                    <td>
                        <select name="sangoma_t1mode">
EOF;
        $t1 = $settings['t1mode'] == 'T1' ? 'selected' : '';
        $e1 = $settings['t1mode'] == 'E1' ? 'selected' : '';
        $output['html'] .= '<option value="T1" '.$t1.'>T1</option>';
        $output['html'] .= '<option value="E1" '.$e1.'>E1</option>';
        $output['html'] .= <<< EOF
                        </select>
                    </td>
                </tr>
            </table>
EOF;
        $output['javascript'] = <<< EOF
        $('#sangoma_dahdimode').change(function() {
            val = $(this).val()
            if(val == 'yes') {
                $('#sangoma_t1mode').show()
            } else {
                $('#sangoma_t1mode').hide()
            }
        });
EOF;
        return $output;
    }
    
    public function settings_process($type,$settings) {
        $this->check_wanrouter();
        $n = array();
        if($type == 'sangomasettingssubmit') {
            foreach($this->sangoma_settings as $key => $default_value) {
                if(isset($settings['sangoma_'.$key])) {
                    $n[$key] = $settings['sangoma_'.$key];
                } else {
                    $n[$key] = $settings[$default_value];
                }
            }
            $json_settings = json_encode($n);
            $sql = "REPLACE INTO dahdi_modules (module_name, settings) VALUES ('sangoma', '".mysql_real_escape_string($json_settings)."')";
            sql($sql);
        
            return array("status" => true);
        }
    }
    
	public function get_filename() {
		return array('/etc/wanpipe/global.conf');
	}
    
	public function generateConf($file) {
        global $amp_conf;
        $settings = $this->get_sangoma_settings();
        if(!$amp_conf['DAHDIDISABLEWRITE']) {
    		switch($file) {
                case '/etc/wanpipe/global.conf':
                    if($settings['dahdimode'] == 'yes') {
                        $output = "WANPIPE_GLOBAL_CFG=DAHDI\nWANPIPE_GLOBAL_FE_MEDIA=".$settings['t1mode'];
                        file_put_contents($file, $output);
                    } elseif(file_exists($file)) {
                        if(!unlink($file)) {
                            global $db;
                            $nt =& notifications::create($db);
                			$nt->add_error('dahdiconfig', 'SANGOMA', _('Unable to delete '.$file), "Please change permissions on ".$file, "", false, true);
                        }
                    }
                    break;
                default:
                    break;
            }
        }
    }
    
    private function check_wanrouter() {
        /*
        $binary = exec('which wanrouter');
        if($binary) {
            $version = exec($binary.' version');
            dbug($version);
        }
        */
    }
}
